import { Facing } from "./plot";
import { RoomName } from "./rooms";
import { RoomOpening } from "./solve";
import { CustomDim } from "@/components/RoomCustomizer";

export interface ModelBlueprint {
  id: string;
  name: string;
  type: "1BHK" | "2BHK" | "3BHK" | "4BHK";
  plotSizeLabel: string;
  plotWidthFt: number;
  plotDepthFt: number;
  facing: Facing;
  builtUpAreaSqFt: number;
  totalSqFt: number;
  vaastuRating: string;
  description: string;
  highlights: string[];
  counts: Record<RoomName, number>;
  customDims: Record<string, CustomDim>;
  customPositions?: Record<string, { xFt: number; yFt: number }>;
  customOpenings?: Record<string, RoomOpening[]>;
  customWallThickness?: Record<string, number>;
}

export const MODEL_BLUEPRINTS: ModelBlueprint[] = [
  // 0. 36x48 (1,728 sq ft) — Parisian Haute Penthouse Dollhouse
  {
    id: "parisian_haute_penthouse",
    name: "Parisian Haute Penthouse & Salon",
    type: "3BHK",
    plotSizeLabel: "36×48 (1,728 sq ft)",
    plotWidthFt: 36,
    plotDepthFt: 48,
    facing: "N",
    builtUpAreaSqFt: 1052,
    totalSqFt: 1728,
    vaastuRating: "Architectural Showcase",
    description:
      "A grand French Parisian open-concept penthouse with Chevron blonde oak parquet, boiserie picture paneling, salon living room with classical fireplace, grand Nero Marquina dining room, and an open-concept walnut chef kitchen.",
    highlights: [
      "Parisian Salon Living with Fireplace Alcove",
      "Grand 10-Seater Nero Marquina Dining Hall",
      "Open Smoked Walnut Chef Kitchen & Breakfast Island",
      "French Chevron Oak & Boiserie Wall Molding",
    ],
    counts: {
      hall: 1,
      kitchen: 1,
      dining: 1,
      bedroom: 2,
      bathroom: 2,
      pooja: 0,
      store: 1,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 16, dFt: 18 },
      dining_0: { wFt: 14, dFt: 18 },
      bedroom_0: { wFt: 16, dFt: 14 },
      kitchen_0: { wFt: 14, dFt: 14 },
      bedroom_1: { wFt: 14, dFt: 8 },
      bathroom_0: { wFt: 6, dFt: 8 },
      bathroom_1: { wFt: 5, dFt: 8 },
      store_0: { wFt: 5, dFt: 8 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      dining_0: { xFt: 16, yFt: 0 },
      bedroom_0: { xFt: 0, yFt: 18 },
      kitchen_0: { xFt: 16, yFt: 18 },
      bedroom_1: { xFt: 0, yFt: 32 },
      bathroom_0: { xFt: 14, yFt: 32 },
      bathroom_1: { xFt: 20, yFt: 32 },
      store_0: { xFt: 25, yFt: 32 },
    },
  },

  // 1. 20x30 (600 sq ft) — 1BHK Urban Sanctuary
  {
    id: "20x30_1bhk_north",
    name: "Urban 1BHK Studio Sanctuary",
    type: "1BHK",
    plotSizeLabel: "20×30 (600 sq ft)",
    plotWidthFt: 20,
    plotDepthFt: 30,
    facing: "N",
    builtUpAreaSqFt: 329,
    totalSqFt: 600,
    vaastuRating: "100% Vaastu Compliant",
    description:
      "A smart, ultra-efficient compact home designed for urban plots. Features an airy front living room, a Vaastu-compliant South-East kitchen, and a private master bedroom suite.",
    highlights: [
      "Open-concept Living & Dining",
      "Agni Kitchen in South-East",
      "Master Suite in South-West",
      "Zero Corridor Space Waste",
    ],
    counts: {
      hall: 1,
      kitchen: 1,
      dining: 0,
      bedroom: 1,
      bathroom: 1,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 10, dFt: 12 },
      kitchen_0: { wFt: 6, dFt: 12 },
      bedroom_0: { wFt: 10, dFt: 11 },
      bathroom_0: { wFt: 6, dFt: 7 },
      pooja_0: { wFt: 6, dFt: 4 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      kitchen_0: { xFt: 10, yFt: 0 },
      bedroom_0: { xFt: 0, yFt: 12 },
      bathroom_0: { xFt: 10, yFt: 12 },
      pooja_0: { xFt: 10, yFt: 19 },
    },
  },

  // 2. 20x30 (600 sq ft) — 2BHK Starter Haven
  {
    id: "20x30_2bhk_east",
    name: "Compact 2BHK Starter Haven",
    type: "2BHK",
    plotSizeLabel: "20×30 (600 sq ft)",
    plotWidthFt: 20,
    plotDepthFt: 30,
    facing: "E",
    builtUpAreaSqFt: 344,
    totalSqFt: 600,
    vaastuRating: "East-Facing Sunlit",
    description:
      "Clever dual-bedroom layout maximizing every square inch with morning natural sunlight, dual bedrooms, and a central gathering hall.",
    highlights: [
      "East-Facing Morning Sunlight",
      "Two Cozy Bedrooms",
      "Optimized Cross-Ventilation",
      "Efficient Kitchen & Bath",
    ],
    counts: {
      hall: 1,
      kitchen: 1,
      dining: 0,
      bedroom: 2,
      bathroom: 1,
      pooja: 0,
      store: 0,
      entrance: 0,
    },
    customDims: {
      kitchen_0: { wFt: 6, dFt: 12 },
      hall_0: { wFt: 10, dFt: 12 },
      bedroom_0: { wFt: 9, dFt: 11 },
      bedroom_1: { wFt: 7, dFt: 6 },
      bathroom_0: { wFt: 7, dFt: 5 },
    },
    customPositions: {
      kitchen_0: { xFt: 0, yFt: 0 },
      hall_0: { xFt: 6, yFt: 0 },
      bedroom_0: { xFt: 0, yFt: 12 },
      bedroom_1: { xFt: 9, yFt: 12 },
      bathroom_0: { xFt: 9, yFt: 18 },
    },
  },

  // 3. 20x40 (800 sq ft) — 2BHK Narrow-Lot Smart Home
  {
    id: "20x40_2bhk_north",
    name: "Narrow-Lot 2BHK Smart Home",
    type: "2BHK",
    plotSizeLabel: "20×40 (800 sq ft)",
    plotWidthFt: 20,
    plotDepthFt: 40,
    facing: "N",
    builtUpAreaSqFt: 512,
    totalSqFt: 800,
    vaastuRating: "100% Vaastu Compliant",
    description:
      "Engineered specifically for narrow frontages with deep lot profiles. Features a generous North-East living lounge, separate dining, South-East modular kitchen, and two private rear bedrooms.",
    highlights: [
      "Optimized for 20 ft Narrow Frontage",
      "North-East Sunlit Living Lounge",
      "Dedicated Dining & Agni Kitchen",
      "Dual Master & Guest Bedrooms",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 1,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 10, dFt: 14 },
      pooja_0: { wFt: 6, dFt: 5 },
      dining_0: { wFt: 6, dFt: 9 },
      bedroom_1: { wFt: 9, dFt: 10 },
      kitchen_0: { wFt: 7, dFt: 10 },
      bedroom_0: { wFt: 10, dFt: 8 },
      bathroom_0: { wFt: 6, dFt: 8 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 10, yFt: 0 },
      dining_0: { xFt: 10, yFt: 5 },
      bedroom_1: { xFt: 0, yFt: 14 },
      kitchen_0: { xFt: 9, yFt: 14 },
      bedroom_0: { xFt: 0, yFt: 24 },
      bathroom_0: { xFt: 10, yFt: 24 },
    },
  },

  // 4. 25x40 (1,000 sq ft) — 2BHK Eco-Villa
  {
    id: "25x40_2bhk_east",
    name: "Modern 2BHK Eco-Villa",
    type: "2BHK",
    plotSizeLabel: "25×40 (1,000 sq ft)",
    plotWidthFt: 25,
    plotDepthFt: 40,
    facing: "E",
    builtUpAreaSqFt: 640,
    totalSqFt: 1000,
    vaastuRating: "East-Facing Eco-Plan",
    description:
      "A breezy East-facing home planned with cross-ventilation corridors, expansive living lounge, integrated breakfast counter dining, and spacious master suite.",
    highlights: [
      "East-Facing Auspicious Entrance",
      "Open Breakfast Counter & Dining",
      "South-West Master Bedroom Suite",
      "Cross-Ventilated Double Windows",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 1,
      pooja: 0,
      store: 0,
      entrance: 0,
    },
    customDims: {
      kitchen_0: { wFt: 8, dFt: 10 },
      dining_0: { wFt: 8, dFt: 6 },
      hall_0: { wFt: 12, dFt: 16 },
      bedroom_0: { wFt: 11, dFt: 16 },
      bedroom_1: { wFt: 9, dFt: 10 },
      bathroom_0: { wFt: 9, dFt: 6 },
    },
    customPositions: {
      kitchen_0: { xFt: 0, yFt: 0 },
      dining_0: { xFt: 0, yFt: 10 },
      hall_0: { xFt: 8, yFt: 0 },
      bedroom_0: { xFt: 0, yFt: 16 },
      bedroom_1: { xFt: 11, yFt: 16 },
      bathroom_0: { xFt: 11, yFt: 26 },
    },
  },

  // 5. 25x50 (1,250 sq ft) — 3BHK Urban Retreat
  {
    id: "25x50_3bhk_north",
    name: "Contemporary 3BHK Urban Retreat",
    type: "3BHK",
    plotSizeLabel: "25×50 (1,250 sq ft)",
    plotWidthFt: 25,
    plotDepthFt: 50,
    facing: "N",
    builtUpAreaSqFt: 840,
    totalSqFt: 1250,
    vaastuRating: "100% Vaastu Compliant",
    description:
      "A high-efficiency 3BHK residence on a 25×50 plot. Boasts an impressive living lounge, private pooja mandir, separate dining, and 3 full-sized bedrooms.",
    highlights: [
      "3 Full-Sized Private Bedrooms",
      "North-Facing Light-Filled Hall",
      "Dedicated Ishanya Pooja Mandir",
      "Generous Dining & Kitchen Hub",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 3,
      bathroom: 1,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 12, dFt: 16 },
      pooja_0: { wFt: 8, dFt: 6 },
      dining_0: { wFt: 8, dFt: 10 },
      bedroom_1: { wFt: 11, dFt: 12 },
      kitchen_0: { wFt: 9, dFt: 12 },
      bedroom_0: { wFt: 11, dFt: 14 },
      bedroom_2: { wFt: 9, dFt: 9 },
      bathroom_0: { wFt: 9, dFt: 5 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 12, yFt: 0 },
      dining_0: { xFt: 12, yFt: 6 },
      bedroom_1: { xFt: 0, yFt: 16 },
      kitchen_0: { xFt: 11, yFt: 16 },
      bedroom_0: { xFt: 0, yFt: 28 },
      bedroom_2: { xFt: 11, yFt: 28 },
      bathroom_0: { xFt: 11, yFt: 37 },
    },
  },

  // 6. 30x40 (1,200 sq ft) — 2BHK Classic Vaastu Home
  {
    id: "30x40_2bhk_north",
    name: "Classic 2BHK Vaastu Residence",
    type: "2BHK",
    plotSizeLabel: "30×40 (1,200 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 40,
    facing: "N",
    builtUpAreaSqFt: 748,
    totalSqFt: 1200,
    vaastuRating: "100% Vaastu Compliant",
    description:
      "The quintessential Indian family home plan. Spacious living hall with North-East entry, dedicated dining space, South-East modular kitchen, Ishanya Pooja mandir, and South-West Master Suite.",
    highlights: [
      "North-East Main Entry",
      "South-West Master Bedroom",
      "South-East Agni Modular Kitchen",
      "Formal Dining Hall & Pooja Mandir",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 2,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 10, dFt: 10 },
      pooja_0: { wFt: 5, dFt: 6 },
      bathroom_1: { wFt: 5, dFt: 6 },
      hall_0: { wFt: 14, dFt: 16 },
      bedroom_0: { wFt: 14, dFt: 16 },
      kitchen_0: { wFt: 10, dFt: 10 },
      bathroom_0: { wFt: 10, dFt: 6 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 0, yFt: 10 },
      bathroom_1: { xFt: 5, yFt: 10 },
      hall_0: { xFt: 10, yFt: 0 },
      bedroom_0: { xFt: 0, yFt: 16 },
      kitchen_0: { xFt: 14, yFt: 16 },
      bathroom_0: { xFt: 14, yFt: 26 },
    },
  },

  // 7. 30x40 (1,200 sq ft) — 3BHK Modern Family Residence
  {
    id: "30x40_3bhk_east",
    name: "Modern 3BHK Family Residence",
    type: "3BHK",
    plotSizeLabel: "30×40 (1,200 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 40,
    facing: "E",
    builtUpAreaSqFt: 755,
    totalSqFt: 1200,
    vaastuRating: "East-Facing Master Plan",
    description:
      "A high-demand 3-bedroom blueprint crafted for growing families. Generous living area, three well-proportioned bedrooms, separate dining and pantry store room.",
    highlights: [
      "3 Private Bedrooms",
      "East-Facing Entrance",
      "Dedicated Pantry / Store Room",
      "Optimal Privacy Zoning",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 3,
      bathroom: 2,
      pooja: 0,
      store: 1,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 11, dFt: 10 },
      kitchen_0: { wFt: 11, dFt: 6 },
      hall_0: { wFt: 13, dFt: 16 },
      bedroom_0: { wFt: 13, dFt: 16 },
      bedroom_1: { wFt: 11, dFt: 11 },
      bathroom_0: { wFt: 6, dFt: 5 },
      bathroom_1: { wFt: 5, dFt: 5 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      kitchen_0: { xFt: 0, yFt: 10 },
      hall_0: { xFt: 11, yFt: 0 },
      bedroom_0: { xFt: 0, yFt: 16 },
      bedroom_1: { xFt: 13, yFt: 16 },
      bathroom_0: { xFt: 13, yFt: 27 },
      bathroom_1: { xFt: 19, yFt: 27 },
    },
  },

  // 8. 30x40 (1,200 sq ft) — 2BHK South-Facing Haven
  {
    id: "30x40_2bhk_south",
    name: "Auspicious 2BHK South-Facing Haven",
    type: "2BHK",
    plotSizeLabel: "30×40 (1,200 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 40,
    facing: "S",
    builtUpAreaSqFt: 768,
    totalSqFt: 1200,
    vaastuRating: "100% Vaastu Compliant",
    description:
      "Expertly configured for South-facing plots following traditional Agni entrance pada. Places the front living hall in the South-East, kitchen in Agni zone, and master suite securely in South-West.",
    highlights: [
      "South-East Auspicious Entrance",
      "South-West Master Retreat",
      "North-East Light-Filled Pooja & Dining",
      "Cross-Breeze Optimized Bedrooms",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 1,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      bedroom_1: { wFt: 12, dFt: 14 },
      pooja_0: { wFt: 6, dFt: 6 },
      bathroom_0: { wFt: 6, dFt: 6 },
      dining_0: { wFt: 12, dFt: 8 },
      bedroom_0: { wFt: 13, dFt: 18 },
      kitchen_0: { wFt: 11, dFt: 8 },
      hall_0: { wFt: 11, dFt: 10 },
    },
    customPositions: {
      bedroom_1: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 12, yFt: 0 },
      bathroom_0: { xFt: 18, yFt: 0 },
      dining_0: { xFt: 12, yFt: 6 },
      bedroom_0: { xFt: 0, yFt: 14 },
      kitchen_0: { xFt: 13, yFt: 14 },
      hall_0: { xFt: 13, yFt: 22 },
    },
  },

  // 9. 30x40 (1,200 sq ft) — 3BHK West-Facing Sunset Home
  {
    id: "30x40_3bhk_west",
    name: "Sunset Glow 3BHK West-Facing Home",
    type: "3BHK",
    plotSizeLabel: "30×40 (1,200 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 40,
    facing: "W",
    builtUpAreaSqFt: 768,
    totalSqFt: 1200,
    vaastuRating: "West-Facing Master Plan",
    description:
      "A harmonious West-facing plan aligned with Varuna devata. Welcomes guests through the North-West entry lounge, with serene North-East pooja and commanding South-West master suite.",
    highlights: [
      "West-Facing Warm Living Lounge",
      "North-East Sacred Pooja Mandir",
      "South-West Master Sanctuary",
      "Dual Full Bathrooms & Dining",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 2,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 13, dFt: 16 },
      pooja_0: { wFt: 5, dFt: 6 },
      kitchen_0: { wFt: 6, dFt: 6 },
      dining_0: { wFt: 11, dFt: 10 },
      bedroom_0: { wFt: 13, dFt: 16 },
      bedroom_1: { wFt: 11, dFt: 11 },
      bathroom_0: { wFt: 6, dFt: 5 },
      bathroom_1: { wFt: 5, dFt: 5 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 13, yFt: 0 },
      kitchen_0: { xFt: 18, yFt: 0 },
      dining_0: { xFt: 13, yFt: 6 },
      bedroom_0: { xFt: 0, yFt: 16 },
      bedroom_1: { xFt: 13, yFt: 16 },
      bathroom_0: { xFt: 13, yFt: 27 },
      bathroom_1: { xFt: 19, yFt: 27 },
    },
  },

  // 10. 30x50 (1,500 sq ft) — 3BHK Contemporary Villa
  {
    id: "30x50_3bhk_east",
    name: "Contemporary 3BHK with Pooja & Dining",
    type: "3BHK",
    plotSizeLabel: "30×50 (1,500 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 50,
    facing: "E",
    builtUpAreaSqFt: 1009,
    totalSqFt: 1500,
    vaastuRating: "100% Vaastu Compliant",
    description:
      "A grand 1,500 sq ft layout with elongated depth. Expansive living hall, formal dining, chef's kitchen with attached utility/store, luxurious master suite with ensuite bath, and sacred pooja mandir.",
    highlights: [
      "Expansive 14×18 ft Living Salon",
      "Private Master Suite in South-West",
      "Dedicated Ishanya Pooja Room",
      "Walk-in Pantry Store & Dining",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 3,
      bathroom: 2,
      pooja: 1,
      store: 1,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 10, dFt: 12 },
      pooja_0: { wFt: 5, dFt: 6 },
      store_0: { wFt: 5, dFt: 6 },
      hall_0: { wFt: 14, dFt: 18 },
      bedroom_1: { wFt: 14, dFt: 12 },
      kitchen_0: { wFt: 10, dFt: 12 },
      bedroom_0: { wFt: 14, dFt: 12 },
      bathroom_0: { wFt: 5, dFt: 12 },
      bathroom_1: { wFt: 5, dFt: 12 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 0, yFt: 12 },
      store_0: { xFt: 5, yFt: 12 },
      hall_0: { xFt: 10, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 18 },
      kitchen_0: { xFt: 14, yFt: 18 },
      bedroom_0: { xFt: 0, yFt: 30 },
      bathroom_0: { xFt: 14, yFt: 30 },
      bathroom_1: { xFt: 19, yFt: 30 },
    },
  },

  // 11. 30x50 (1,500 sq ft) — 2BHK Sunlit Villa
  {
    id: "30x50_2bhk_north",
    name: "Sunlit 2BHK + Grand Living Villa",
    type: "2BHK",
    plotSizeLabel: "30×50 (1,500 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 50,
    facing: "N",
    builtUpAreaSqFt: 1009,
    totalSqFt: 1500,
    vaastuRating: "Premium North-Facing",
    description:
      "Designed for spacious living with extra-large bedroom suites, huge light-filled living salon, dining overlooking gardens, and maximum setbacks for cross breezes.",
    highlights: [
      "Massive 15×18 ft Living Hall",
      "Two Deluxe Master Bedrooms",
      "North-Facing Sunlit Foyer",
      "Generous Garden Setbacks",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 2,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      pooja_0: { wFt: 9, dFt: 6 },
      dining_0: { wFt: 9, dFt: 12 },
      hall_0: { wFt: 15, dFt: 18 },
      bedroom_1: { wFt: 14, dFt: 14 },
      kitchen_0: { wFt: 10, dFt: 14 },
      bedroom_0: { wFt: 14, dFt: 10 },
      bathroom_0: { wFt: 5, dFt: 10 },
      bathroom_1: { wFt: 5, dFt: 10 },
    },
    customPositions: {
      pooja_0: { xFt: 0, yFt: 0 },
      dining_0: { xFt: 0, yFt: 6 },
      hall_0: { xFt: 9, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 18 },
      kitchen_0: { xFt: 14, yFt: 18 },
      bedroom_0: { xFt: 0, yFt: 32 },
      bathroom_0: { xFt: 14, yFt: 32 },
      bathroom_1: { xFt: 19, yFt: 32 },
    },
  },

  // 12. 35x50 (1,750 sq ft) — Traditional Kerala Courtyard Villa
  {
    id: "35x50_kerala_courtyard",
    name: "Traditional Kerala Courtyard Villa",
    type: "3BHK",
    plotSizeLabel: "35×50 (1,750 sq ft)",
    plotWidthFt: 35,
    plotDepthFt: 50,
    facing: "E",
    builtUpAreaSqFt: 1176,
    totalSqFt: 1750,
    vaastuRating: "100% Vaastu / Thachu Shastra",
    description:
      "Inspired by classical Kerala Nalukettu architecture. Highlights a grand central gathering hall, traditional granary store, pooja sanctum, and airy veranda cross-ventilation.",
    highlights: [
      "Nalukettu Central Gathering Hall",
      "Traditional Granary & Pantry Store",
      "Ishanya Sanctum Pooja Room",
      "Thachu Shastra Auspicious Grid",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 2,
      pooja: 1,
      store: 1,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 12, dFt: 14 },
      pooja_0: { wFt: 6, dFt: 6 },
      store_0: { wFt: 6, dFt: 6 },
      hall_0: { wFt: 16, dFt: 20 },
      bedroom_1: { wFt: 15, dFt: 12 },
      kitchen_0: { wFt: 13, dFt: 12 },
      bedroom_0: { wFt: 15, dFt: 10 },
      bathroom_0: { wFt: 6, dFt: 10 },
      bathroom_1: { wFt: 7, dFt: 10 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 0, yFt: 14 },
      store_0: { xFt: 6, yFt: 14 },
      hall_0: { xFt: 12, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 20 },
      kitchen_0: { xFt: 13, yFt: 20 },
      bedroom_0: { xFt: 0, yFt: 32 },
      bathroom_0: { xFt: 15, yFt: 32 },
      bathroom_1: { xFt: 21, yFt: 32 },
    },
  },

  // 13. 35x50 (1,750 sq ft) — Scandinavian Modernist Villa
  {
    id: "35x50_scandinavian_modern",
    name: "Scandinavian Modernist 3BHK Villa",
    type: "3BHK",
    plotSizeLabel: "35×50 (1,750 sq ft)",
    plotWidthFt: 35,
    plotDepthFt: 50,
    facing: "N",
    builtUpAreaSqFt: 1176,
    totalSqFt: 1750,
    vaastuRating: "Architectural Showcase",
    description:
      "Nordic minimalism featuring floor-to-ceiling glass daylighting, light birch woodwork, seamless open dining, and private bedroom sanctuaries.",
    highlights: [
      "Nordic Light Living & Great Room",
      "Minimalist Birch & Oak Chef Kitchen",
      "Seamless Open-Concept Dining",
      "Master Suite & Utility Store",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 1,
      pooja: 0,
      store: 1,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 16, dFt: 20 },
      dining_0: { wFt: 12, dFt: 20 },
      bedroom_1: { wFt: 14, dFt: 12 },
      kitchen_0: { wFt: 14, dFt: 12 },
      bedroom_0: { wFt: 14, dFt: 10 },
      bathroom_0: { wFt: 7, dFt: 10 },
      store_0: { wFt: 7, dFt: 10 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      dining_0: { xFt: 16, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 20 },
      kitchen_0: { xFt: 14, yFt: 20 },
      bedroom_0: { xFt: 0, yFt: 32 },
      bathroom_0: { xFt: 14, yFt: 32 },
      store_0: { xFt: 21, yFt: 32 },
    },
  },

  // 14. 40x60 (2,400 sq ft) — 3BHK Executive Luxury Bungalow
  {
    id: "40x60_3bhk_north",
    name: "Executive 3BHK Luxury Bungalow",
    type: "3BHK",
    plotSizeLabel: "40×60 (2,400 sq ft)",
    plotWidthFt: 40,
    plotDepthFt: 60,
    facing: "N",
    builtUpAreaSqFt: 1391,
    totalSqFt: 2400,
    vaastuRating: "100% Vaastu Compliant",
    description:
      "An estate-class single-level bungalow with an impressive double-door entrance, formal living salon, banquet-ready dining, gourmet kitchen, pantry store, and three grand king-size bedroom suites with attached baths.",
    highlights: [
      "Palatial Living Salon (19×22 ft)",
      "3 King-Size En-suite Bedrooms",
      "Gourmet Kitchen + Walk-in Store",
      "Sacred Ishanya Corner Pooja",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 3,
      bathroom: 3,
      pooja: 1,
      store: 1,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 14, dFt: 16 },
      pooja_0: { wFt: 6, dFt: 6 },
      store_0: { wFt: 8, dFt: 6 },
      hall_0: { wFt: 19, dFt: 22 },
      bedroom_1: { wFt: 16, dFt: 14 },
      kitchen_0: { wFt: 17, dFt: 14 },
      bedroom_0: { wFt: 16, dFt: 14 },
      bedroom_2: { wFt: 17, dFt: 14 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 0, yFt: 16 },
      store_0: { xFt: 6, yFt: 16 },
      hall_0: { xFt: 14, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 22 },
      kitchen_0: { xFt: 16, yFt: 22 },
      bedroom_0: { xFt: 0, yFt: 36 },
      bedroom_2: { xFt: 16, yFt: 36 },
    },
  },

  // 15. 40x60 (2,400 sq ft) — 4BHK Royal Grand Estate
  {
    id: "40x60_4bhk_east",
    name: "Royal 4BHK Grand Estate",
    type: "4BHK",
    plotSizeLabel: "40×60 (2,400 sq ft)",
    plotWidthFt: 40,
    plotDepthFt: 60,
    facing: "E",
    builtUpAreaSqFt: 1397,
    totalSqFt: 2400,
    vaastuRating: "East-Facing Royal Plan",
    description:
      "A complete 4-bedroom luxury layout offering separate zones for entertaining, private family gatherings, culinary prep, traditional pooja, and 4 dedicated master suites.",
    highlights: [
      "4 Deluxe Bedrooms",
      "East-Facing Auspicious Entrance",
      "Formal Dining & Modular Kitchen",
      "Dedicated Pooja & Storage",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 4,
      bathroom: 3,
      pooja: 1,
      store: 1,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 14, dFt: 14 },
      kitchen_0: { wFt: 14, dFt: 10 },
      hall_0: { wFt: 19, dFt: 24 },
      bedroom_1: { wFt: 16, dFt: 13 },
      bedroom_2: { wFt: 17, dFt: 13 },
      bedroom_0: { wFt: 16, dFt: 13 },
      bedroom_3: { wFt: 17, dFt: 13 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      kitchen_0: { xFt: 0, yFt: 14 },
      hall_0: { xFt: 14, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 24 },
      bedroom_2: { xFt: 16, yFt: 24 },
      bedroom_0: { xFt: 0, yFt: 37 },
      bedroom_3: { xFt: 16, yFt: 37 },
    },
  },

  // 16. 40x60 (2,400 sq ft) — Chettinad Heritage 4BHK Manor
  {
    id: "40x60_chettinad_heritage",
    name: "Chettinad Heritage 4BHK Manor",
    type: "4BHK",
    plotSizeLabel: "40×60 (2,400 sq ft)",
    plotWidthFt: 40,
    plotDepthFt: 60,
    facing: "S",
    builtUpAreaSqFt: 1650,
    totalSqFt: 2400,
    vaastuRating: "100% Traditional Heritage",
    description:
      "Inspired by the palatial mansions of Karaikudi and Chettinad. Features pillared front verandah entrance (Thinnai), grand central courtyard hall, traditional granary, and royal master suites.",
    highlights: [
      "Classical Thinnai Front Living Hall",
      "Pooja Sanctum in Auspicious Ishanya",
      "Grand Feasting Dining Hall",
      "Traditional Granary Store & Kitchen",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 3,
      bathroom: 2,
      pooja: 1,
      store: 1,
      entrance: 0,
    },
    customDims: {
      bedroom_2: { wFt: 16, dFt: 14 },
      pooja_0: { wFt: 8, dFt: 8 },
      store_0: { wFt: 9, dFt: 8 },
      dining_0: { wFt: 17, dFt: 10 },
      bedroom_1: { wFt: 16, dFt: 14 },
      kitchen_0: { wFt: 17, dFt: 10 },
      bedroom_0: { wFt: 16, dFt: 22 },
      hall_0: { wFt: 17, dFt: 22 },
    },
    customPositions: {
      bedroom_2: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 16, yFt: 0 },
      store_0: { xFt: 24, yFt: 0 },
      dining_0: { xFt: 16, yFt: 8 },
      bedroom_1: { xFt: 0, yFt: 14 },
      kitchen_0: { xFt: 16, yFt: 18 },
      bedroom_0: { xFt: 0, yFt: 28 },
      hall_0: { xFt: 16, yFt: 28 },
    },
  },

  // 17. 40x60 (2,400 sq ft) — Japanese Zen Minimalist Villa
  {
    id: "40x60_japanese_zen",
    name: "Japanese Zen Minimalist 3BHK Villa",
    type: "3BHK",
    plotSizeLabel: "40×60 (2,400 sq ft)",
    plotWidthFt: 40,
    plotDepthFt: 60,
    facing: "N",
    builtUpAreaSqFt: 1650,
    totalSqFt: 2400,
    vaastuRating: "Zen Architectural Design",
    description:
      "A serene sanctuary centered around Engawa porch connections, minimalist sliding partitions, open tea room dining, and peaceful nature views.",
    highlights: [
      "Engawa-Inspired Great Room",
      "Shoji Tea & Dining Pavilion",
      "Tatami Wood Guest Suite",
      "Private Master Sanctuary Wing",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 1,
      pooja: 0,
      store: 1,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 19, dFt: 22 },
      dining_0: { wFt: 14, dFt: 22 },
      bedroom_1: { wFt: 16, dFt: 14 },
      kitchen_0: { wFt: 17, dFt: 14 },
      bedroom_0: { wFt: 16, dFt: 14 },
      bathroom_0: { wFt: 8, dFt: 14 },
      store_0: { wFt: 9, dFt: 14 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      dining_0: { xFt: 19, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 22 },
      kitchen_0: { xFt: 16, yFt: 22 },
      bedroom_0: { xFt: 0, yFt: 36 },
      bathroom_0: { xFt: 16, yFt: 36 },
      store_0: { xFt: 24, yFt: 36 },
    },
  },

  // 18. 50x80 (4,000 sq ft) — Palatial Courtyard Mansion
  {
    id: "50x80_4bhk_north",
    name: "Palatial 4BHK Courtyard Mansion",
    type: "4BHK",
    plotSizeLabel: "50×80 (4,000 sq ft)",
    plotWidthFt: 50,
    plotDepthFt: 80,
    facing: "N",
    builtUpAreaSqFt: 1969,
    totalSqFt: 4000,
    vaastuRating: "100% Vaastu Compliant",
    description:
      "A magnificent luxury mansion designed for expansive 50×80 plots. Grand royal salon, banquet dining, chef's kitchen, presidential master wing with private bath, and 3 guest/children suites.",
    highlights: [
      "Royal Grand Salon (24×26 ft)",
      "Presidential Master Wing (20×24 ft)",
      "Chef's Kitchen with Pantry & Store",
      "Traditional Ishanya Pooja Mandir",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 4,
      bathroom: 4,
      pooja: 1,
      store: 1,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 18, dFt: 18 },
      pooja_0: { wFt: 9, dFt: 8 },
      store_0: { wFt: 9, dFt: 8 },
      hall_0: { wFt: 24, dFt: 26 },
      bedroom_1: { wFt: 20, dFt: 18 },
      kitchen_0: { wFt: 22, dFt: 18 },
      bedroom_0: { wFt: 20, dFt: 24 },
      bedroom_2: { wFt: 22, dFt: 12 },
      bedroom_3: { wFt: 22, dFt: 12 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 0, yFt: 18 },
      store_0: { xFt: 9, yFt: 18 },
      hall_0: { xFt: 18, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 26 },
      kitchen_0: { xFt: 20, yFt: 26 },
      bedroom_0: { xFt: 0, yFt: 44 },
      bedroom_2: { xFt: 20, yFt: 44 },
      bedroom_3: { xFt: 20, yFt: 56 },
    },
  },

  // 19. 50x80 (4,000 sq ft) — Royal Sovereign Presidential Villa
  {
    id: "50x80_royal_sovereign",
    name: "Presidential 4BHK Sovereign Villa",
    type: "4BHK",
    plotSizeLabel: "50×80 (4,000 sq ft)",
    plotWidthFt: 50,
    plotDepthFt: 80,
    facing: "E",
    builtUpAreaSqFt: 2856,
    totalSqFt: 4000,
    vaastuRating: "East-Facing Sovereign Plan",
    description:
      "The pinnacle of residential architecture. Features an expansive 24×38 ft Grand Reception Hall, 18×22 ft Banquet Dining, full commercial chef kitchen, and 4 presidential en-suite suites.",
    highlights: [
      "Colossal 24×38 ft Reception Salon",
      "Formal Banquet Dining Room",
      "4 Deluxe Presidential Bedroom Suites",
      "Executive Commercial Chef's Kitchen",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 4,
      bathroom: 4,
      pooja: 0,
      store: 0,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 18, dFt: 22 },
      kitchen_0: { wFt: 18, dFt: 16 },
      hall_0: { wFt: 24, dFt: 38 },
      bedroom_1: { wFt: 21, dFt: 15 },
      bedroom_2: { wFt: 21, dFt: 15 },
      bedroom_0: { wFt: 21, dFt: 15 },
      bedroom_3: { wFt: 21, dFt: 15 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      kitchen_0: { xFt: 0, yFt: 22 },
      hall_0: { xFt: 18, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 38 },
      bedroom_2: { xFt: 21, yFt: 38 },
      bedroom_0: { xFt: 0, yFt: 53 },
      bedroom_3: { xFt: 21, yFt: 53 },
    },
  },
];
