import { Facing } from "./plot";
import { ProgramKey } from "./programs";
import { RoomName } from "./rooms";
import { RoomOpening } from "./solve";
import { CustomDim } from "@/components/RoomCustomizer";
import { HouseMaterialConfig } from "./materialsCatalog";

export interface ModelBlueprint {
  id: string;
  name: string;
  /**
   * Layout class, and what the modal's type filter chips list. A residence uses "1BHK".."4BHK";
   * a cafe uses its trade format ("Takeaway", "Coffee Bar", "Cafe", "Roastery", ...). Left as a
   * plain string because the vocabulary belongs to the programme, not to this type.
   */
  type: string;
  /** Which building programme this plan belongs to. Absent means the residence. */
  program?: ProgramKey;
  plotSizeLabel: string;
  plotWidthFt: number;
  plotDepthFt: number;
  facing: Facing;
  builtUpAreaSqFt: number;
  totalSqFt: number;
  /**
   * One-line quality claim shown on the card. Vaastu compliance for a residence, service-flow
   * wording for a cafe — never Vaastu for a plan that never checked it.
   */
  rating: string;
  description: string;
  highlights: string[];
  // Sparse: a blueprint names the rooms it uses. Widen with withCounts() before it hits state.
  counts: Partial<Record<RoomName, number>>;
  customDims: Record<string, CustomDim>;
  customPositions?: Record<string, { xFt: number; yFt: number }>;
  customOpenings?: Record<string, RoomOpening[]>;
  customWallThickness?: Record<string, number>;
  /**
   * Storeys this plan is drawn for, ground included. Absent or 1 is a single-storey plan, which
   * is what every plan here was before the solver could pack more than one. A duplex sets 2 and
   * the mix is split across the floors on the way to the solver — backend/api/main.py.
   */
  floors?: number;
  /**
   * The finishes this plan is drawn with — the facade colour, the glazing, the floors. Partial:
   * whatever it names is laid over the current config, and everything it does not name is left
   * alone. A plan reconstructed from an elevation is mostly this.
   */
  materialConfig?: Partial<HouseMaterialConfig>;
}

export const MODEL_BLUEPRINTS: ModelBlueprint[] = [
  // ---------------------------------------------------------------------------
  // Duplexes. Every one of these is G+1: `floors: 2` sends the mix to the solver
  // to be split across two storeys with a stair core on each — see
  // notes/decisions/bye-law-and-storeys.md. The room programmes and sizes below
  // are taken from published Indian plans for the same plot sizes, listed in
  // notes/blueprints/duplex-sources.md, not invented.
  // ---------------------------------------------------------------------------
  {
    id: "duplex_30x50_glazed_stair_tower",
    name: "30×50 Duplex — Glazed Stair Tower",
    type: "Duplex 3BHK",
    plotSizeLabel: "30×50 (1,500 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 50,
    facing: "E",
    floors: 2,
    builtUpAreaSqFt: 1240,
    totalSqFt: 1500,
    rating: "Vaastu Compliant",
    description:
      "Built from a street elevation, not a plan: a G+1 whose stair core is expressed as a full-height glazed tower on the front, with the porch beside it and a balcony over it. Charcoal render, brick accent and black metal, as drawn. The room layout is the solver's own - an elevation cannot say where a bedroom goes.",
    highlights: [
      "Stair core glazed floor to ceiling, the way the elevation draws it",
      "Charcoal render with a warm brick accent and black metal",
      "3BHK over two storeys, parents' bedroom on the ground",
      "Terrace over the first floor, reachable from the stair",
    ],
    counts: { hall: 1, dining: 1, kitchen: 1, bedroom: 3, bathroom: 3, pooja: 1, store: 1 },
    customDims: {
      hall_0: { wFt: 15, dFt: 13 },
      dining_0: { wFt: 12, dFt: 10 },
      kitchen_0: { wFt: 11, dFt: 9 },
      bedroom_0: { wFt: 12, dFt: 11 },
      bedroom_1: { wFt: 14, dFt: 12 },
      bedroom_2: { wFt: 11, dFt: 11 },
      bathroom_0: { wFt: 7, dFt: 5 },
      bathroom_1: { wFt: 8, dFt: 5 },
      bathroom_2: { wFt: 7, dFt: 5 },
      pooja_0: { wFt: 5, dFt: 4 },
      store_0: { wFt: 6, dFt: 5 },
    },
    // The facade the elevation actually shows. Only the stair core is glazed - that tower is the
    // whole idea of the front - and the rest is charcoal render with a terracotta accent on the
    // hall, which is as close as the palette gets to the exposed brick strip.
    materialConfig: {
      globalWallColor: "charcoal_slate",
      globalFloor: "scandi_grey_ash",
      globalDoorColor: "charcoal_slate",
      roomFloors: { hall: "terrazzo_venice", pooja: "botticino_gold" },
      roomWallColors: { hall: "terracotta", pooja: "champagne_gold" },
      roomGlazing: {
        stairs: { styleId: "structural", wall: true, door: false, mullions: 3 },
      },
    },
  },
  {
    id: "duplex_30x40_3bhk",
    name: "30×40 Duplex — 3BHK G+1",
    type: "Duplex 3BHK",
    plotSizeLabel: "30×40 (1,200 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 40,
    facing: "E",
    floors: 2,
    builtUpAreaSqFt: 1150,
    totalSqFt: 1200,
    rating: "Vaastu Compliant",
    description:
      "The standard Bengaluru and Hyderabad duplex on a 30×40 site: living, dining and kitchen on the ground with a parents' bedroom and its bathroom, and the master plus a second bedroom upstairs off the landing.",
    highlights: [
      "Ground: 12×14 living, dining, kitchen with utility",
      "Parents' bedroom and bathroom kept on the ground floor",
      "First: 12×14 master with ensuite, 10×10 second bedroom",
      "Stair core solved on both floors, not drawn by hand",
    ],
    counts: { hall: 1, dining: 1, kitchen: 1, bedroom: 3, bathroom: 2, pooja: 1 },
    customDims: {
      hall_0: { wFt: 14, dFt: 12 },
      dining_0: { wFt: 11, dFt: 10 },
      kitchen_0: { wFt: 10, dFt: 9 },
      bedroom_0: { wFt: 11, dFt: 11 },
      bedroom_1: { wFt: 14, dFt: 12 },
      bedroom_2: { wFt: 10, dFt: 10 },
      bathroom_0: { wFt: 7, dFt: 5 },
      bathroom_1: { wFt: 7, dFt: 5 },
      pooja_0: { wFt: 5, dFt: 4 },
    },
  },
  {
    id: "duplex_30x50_4bhk",
    name: "30×50 Duplex — 4BHK G+1",
    type: "Duplex 4BHK",
    plotSizeLabel: "30×50 (1,500 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 50,
    facing: "E",
    floors: 2,
    builtUpAreaSqFt: 1330,
    totalSqFt: 1500,
    rating: "Vaastu Compliant",
    description:
      "An east-facing 30×50 duplex with the living room to the north-east and the kitchen north-west, the two positions Vaastu and cross-ventilation both want. Four bedrooms across two floors, with a dedicated pooja room off the hall.",
    highlights: [
      "Living north-east, kitchen north-west on an east-facing plot",
      "Dedicated pooja room, not a niche in the hall",
      "Pooja room and store, both off the hall rather than in it",
      "Three bedrooms upstairs, parents' room on the ground",
    ],
    counts: { hall: 1, dining: 1, kitchen: 1, bedroom: 4, bathroom: 3, pooja: 1, store: 1 },
    customDims: {
      hall_0: { wFt: 15, dFt: 13 },
      dining_0: { wFt: 12, dFt: 11 },
      kitchen_0: { wFt: 11, dFt: 9 },
      bedroom_0: { wFt: 12, dFt: 11 },
      bedroom_1: { wFt: 14, dFt: 13 },
      bedroom_2: { wFt: 11, dFt: 11 },
      bedroom_3: { wFt: 10, dFt: 10 },
      bathroom_0: { wFt: 7, dFt: 5 },
      bathroom_1: { wFt: 8, dFt: 5 },
      bathroom_2: { wFt: 7, dFt: 5 },
      pooja_0: { wFt: 5, dFt: 4 },
      store_0: { wFt: 6, dFt: 5 },
    },
  },
  {
    id: "duplex_40x60_4bhk",
    name: "40×60 Duplex — 4BHK Villa G+1",
    type: "Duplex 4BHK",
    plotSizeLabel: "40×60 (2,400 sq ft)",
    plotWidthFt: 40,
    plotDepthFt: 60,
    facing: "N",
    floors: 2,
    builtUpAreaSqFt: 1760,
    totalSqFt: 2400,
    rating: "Vaastu Compliant",
    description:
      "The villa end of the duplex range on a 40×60 site: a 16×18 living hall, an island kitchen, a guest bedroom on the ground and a 12×16 master suite upstairs with two more bedrooms.",
    highlights: [
      "16×18 living hall opening onto the dining",
      "10×14 island kitchen with utility and store",
      "12×16 master suite upstairs, 12×12 and 10×12 beyond it",
      "Guest bedroom and bathroom on the ground floor",
    ],
    counts: { hall: 1, dining: 1, kitchen: 1, bedroom: 4, bathroom: 3, pooja: 1, store: 1 },
    customDims: {
      hall_0: { wFt: 18, dFt: 16 },
      dining_0: { wFt: 14, dFt: 12 },
      kitchen_0: { wFt: 14, dFt: 10 },
      bedroom_0: { wFt: 12, dFt: 11 },
      bedroom_1: { wFt: 16, dFt: 12 },
      bedroom_2: { wFt: 12, dFt: 12 },
      bedroom_3: { wFt: 12, dFt: 10 },
      bathroom_0: { wFt: 8, dFt: 5 },
      bathroom_1: { wFt: 8, dFt: 6 },
      bathroom_2: { wFt: 7, dFt: 5 },
      pooja_0: { wFt: 6, dFt: 4 },
      store_0: { wFt: 7, dFt: 5 },
    },
  },
  {
    id: "duplex_20x30_2bhk",
    name: "20×30 Duplex — Compact 2BHK G+1",
    type: "Duplex 2BHK",
    plotSizeLabel: "20×30 (600 sq ft)",
    plotWidthFt: 20,
    plotDepthFt: 30,
    facing: "S",
    floors: 2,
    builtUpAreaSqFt: 690,
    totalSqFt: 600,
    rating: "Vaastu Compliant",
    description:
      "A 600 sq ft plot goes vertical or it goes nowhere. Living, kitchen and one bedroom on the ground, the second bedroom and its bathroom above — about 492 sq ft of footprint per floor once the setbacks are taken.",
    highlights: [
      "Under 75 sq yd: registration on BuildNow, not a sanctioned permission",
      "One bedroom and bathroom on each floor",
      "Zero side and rear setback in this plot band, so the full width is usable",
      "Circulation kept to the stair core — no passage waste",
    ],
    counts: { hall: 1, kitchen: 1, bedroom: 2, bathroom: 2 },
    customDims: {
      hall_0: { wFt: 12, dFt: 10 },
      kitchen_0: { wFt: 8, dFt: 7 },
      bedroom_0: { wFt: 10, dFt: 10 },
      bedroom_1: { wFt: 11, dFt: 10 },
      bathroom_0: { wFt: 6, dFt: 4 },
      bathroom_1: { wFt: 6, dFt: 4 },
    },
  },
  // 0. 36x48 (1,728 sq ft) — Parisian Haute Penthouse Dollhouse
  {
    id: "parisian_haute_penthouse",
    name: "Parisian Haute Penthouse & Salon",
    type: "3BHK",
    plotSizeLabel: "36×48 (1,728 sq ft)",
    plotWidthFt: 36,
    plotDepthFt: 48,
    facing: "N",
    builtUpAreaSqFt: 1052,
    totalSqFt: 1728,
    rating: "Architectural Showcase",
    description:
      "A grand French Parisian open-concept penthouse with Chevron blonde oak parquet, boiserie picture paneling, salon living room with classical fireplace, grand Nero Marquina dining room, and an open-concept walnut chef kitchen.",
    highlights: [
      "Parisian Salon Living with Fireplace Alcove",
      "Grand 10-Seater Nero Marquina Dining Hall",
      "Open Smoked Walnut Chef Kitchen & Breakfast Island",
      "French Chevron Oak & Boiserie Wall Molding",
    ],
    counts: {
      hall: 1,
      kitchen: 1,
      dining: 1,
      bedroom: 2,
      bathroom: 2,
      pooja: 0,
      store: 1,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 16, dFt: 18 },
      dining_0: { wFt: 14, dFt: 18 },
      bedroom_0: { wFt: 16, dFt: 14 },
      kitchen_0: { wFt: 14, dFt: 14 },
      bedroom_1: { wFt: 14, dFt: 8 },
      bathroom_0: { wFt: 6, dFt: 8 },
      bathroom_1: { wFt: 5, dFt: 8 },
      store_0: { wFt: 5, dFt: 8 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      dining_0: { xFt: 16, yFt: 0 },
      bedroom_0: { xFt: 0, yFt: 18 },
      kitchen_0: { xFt: 16, yFt: 18 },
      bedroom_1: { xFt: 0, yFt: 32 },
      bathroom_0: { xFt: 14, yFt: 32 },
      bathroom_1: { xFt: 20, yFt: 32 },
      store_0: { xFt: 25, yFt: 32 },
    },
  },

  // 1. 20x30 (600 sq ft) — 1BHK Urban Sanctuary
  {
    id: "20x30_1bhk_north",
    name: "Urban 1BHK Studio Sanctuary",
    type: "1BHK",
    plotSizeLabel: "20×30 (600 sq ft)",
    plotWidthFt: 20,
    plotDepthFt: 30,
    facing: "N",
    builtUpAreaSqFt: 329,
    totalSqFt: 600,
    rating: "100% Vaastu Compliant",
    description:
      "Compact plan for tight urban plots. Front living room on the road side, Agneya kitchen, master bedroom off the rear.",
    highlights: [
      "Open-concept Living & Dining",
      "Agni Kitchen in South-East",
      "Master Suite in South-West",
      "Zero Corridor Space Waste",
    ],
    counts: {
      hall: 1,
      kitchen: 1,
      dining: 0,
      bedroom: 1,
      bathroom: 1,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 10, dFt: 12 },
      kitchen_0: { wFt: 6, dFt: 12 },
      bedroom_0: { wFt: 10, dFt: 11 },
      bathroom_0: { wFt: 6, dFt: 7 },
      pooja_0: { wFt: 6, dFt: 4 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      kitchen_0: { xFt: 10, yFt: 0 },
      bedroom_0: { xFt: 0, yFt: 12 },
      bathroom_0: { xFt: 10, yFt: 12 },
      pooja_0: { xFt: 10, yFt: 19 },
    },
  },

  // 2. 20x30 (600 sq ft) — 2BHK Starter Haven
  {
    id: "20x30_2bhk_east",
    name: "Compact 2BHK Starter Haven",
    type: "2BHK",
    plotSizeLabel: "20×30 (600 sq ft)",
    plotWidthFt: 20,
    plotDepthFt: 30,
    facing: "E",
    builtUpAreaSqFt: 344,
    totalSqFt: 600,
    rating: "East-Facing Sunlit",
    description:
      "Clever dual-bedroom layout maximizing every square inch with morning natural sunlight, dual bedrooms, and a central gathering hall.",
    highlights: [
      "East-Facing Morning Sunlight",
      "Two Cozy Bedrooms",
      "Optimized Cross-Ventilation",
      "Efficient Kitchen & Bath",
    ],
    counts: {
      hall: 1,
      kitchen: 1,
      dining: 0,
      bedroom: 2,
      bathroom: 1,
      pooja: 0,
      store: 0,
      entrance: 0,
    },
    customDims: {
      kitchen_0: { wFt: 6, dFt: 12 },
      hall_0: { wFt: 10, dFt: 12 },
      bedroom_0: { wFt: 9, dFt: 11 },
      bedroom_1: { wFt: 7, dFt: 6 },
      bathroom_0: { wFt: 7, dFt: 5 },
    },
    customPositions: {
      kitchen_0: { xFt: 0, yFt: 0 },
      hall_0: { xFt: 6, yFt: 0 },
      bedroom_0: { xFt: 0, yFt: 12 },
      bedroom_1: { xFt: 9, yFt: 12 },
      bathroom_0: { xFt: 9, yFt: 18 },
    },
  },

  // 3. 20x40 (800 sq ft) — 2BHK Narrow-Lot Smart Home
  {
    id: "20x40_2bhk_north",
    name: "Narrow-Lot 2BHK",
    type: "2BHK",
    plotSizeLabel: "20×40 (800 sq ft)",
    plotWidthFt: 20,
    plotDepthFt: 40,
    facing: "N",
    builtUpAreaSqFt: 512,
    totalSqFt: 800,
    rating: "100% Vaastu Compliant",
    description:
      "Engineered specifically for narrow frontages with deep lot profiles. Features a generous North-East living lounge, separate dining, South-East modular kitchen, and two private rear bedrooms.",
    highlights: [
      "Optimized for 20 ft Narrow Frontage",
      "North-East Sunlit Living Lounge",
      "Dedicated Dining & Agni Kitchen",
      "Dual Master & Guest Bedrooms",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 1,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 10, dFt: 14 },
      pooja_0: { wFt: 6, dFt: 5 },
      dining_0: { wFt: 6, dFt: 9 },
      bedroom_1: { wFt: 9, dFt: 10 },
      kitchen_0: { wFt: 7, dFt: 10 },
      bedroom_0: { wFt: 10, dFt: 8 },
      bathroom_0: { wFt: 6, dFt: 8 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 10, yFt: 0 },
      dining_0: { xFt: 10, yFt: 5 },
      bedroom_1: { xFt: 0, yFt: 14 },
      kitchen_0: { xFt: 9, yFt: 14 },
      bedroom_0: { xFt: 0, yFt: 24 },
      bathroom_0: { xFt: 10, yFt: 24 },
    },
  },

  // 4. 25x40 (1,000 sq ft) — 2BHK Eco-Villa
  {
    id: "25x40_2bhk_east",
    name: "Modern 2BHK Eco-Villa",
    type: "2BHK",
    plotSizeLabel: "25×40 (1,000 sq ft)",
    plotWidthFt: 25,
    plotDepthFt: 40,
    facing: "E",
    builtUpAreaSqFt: 640,
    totalSqFt: 1000,
    rating: "East-Facing Eco-Plan",
    description:
      "A breezy East-facing home planned with cross-ventilation corridors, expansive living lounge, integrated breakfast counter dining, and spacious master suite.",
    highlights: [
      "East-Facing Auspicious Entrance",
      "Open Breakfast Counter & Dining",
      "South-West Master Bedroom Suite",
      "Cross-Ventilated Double Windows",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 1,
      pooja: 0,
      store: 0,
      entrance: 0,
    },
    customDims: {
      kitchen_0: { wFt: 8, dFt: 10 },
      dining_0: { wFt: 8, dFt: 6 },
      hall_0: { wFt: 12, dFt: 16 },
      bedroom_0: { wFt: 11, dFt: 16 },
      bedroom_1: { wFt: 9, dFt: 10 },
      bathroom_0: { wFt: 9, dFt: 6 },
    },
    customPositions: {
      kitchen_0: { xFt: 0, yFt: 0 },
      dining_0: { xFt: 0, yFt: 10 },
      hall_0: { xFt: 8, yFt: 0 },
      bedroom_0: { xFt: 0, yFt: 16 },
      bedroom_1: { xFt: 11, yFt: 16 },
      bathroom_0: { xFt: 11, yFt: 26 },
    },
  },

  // 5. 25x50 (1,250 sq ft) — 3BHK Urban Retreat
  {
    id: "25x50_3bhk_north",
    name: "Contemporary 3BHK Urban Retreat",
    type: "3BHK",
    plotSizeLabel: "25×50 (1,250 sq ft)",
    plotWidthFt: 25,
    plotDepthFt: 50,
    facing: "N",
    builtUpAreaSqFt: 840,
    totalSqFt: 1250,
    rating: "100% Vaastu Compliant",
    description:
      "A high-efficiency 3BHK residence on a 25×50 plot. Boasts an impressive living lounge, private pooja mandir, separate dining, and 3 full-sized bedrooms.",
    highlights: [
      "3 Full-Sized Private Bedrooms",
      "North-Facing Light-Filled Hall",
      "Dedicated Ishanya Pooja Mandir",
      "Generous Dining & Kitchen Hub",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 3,
      bathroom: 1,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 12, dFt: 16 },
      pooja_0: { wFt: 8, dFt: 6 },
      dining_0: { wFt: 8, dFt: 10 },
      bedroom_1: { wFt: 11, dFt: 12 },
      kitchen_0: { wFt: 9, dFt: 12 },
      bedroom_0: { wFt: 11, dFt: 14 },
      bedroom_2: { wFt: 9, dFt: 9 },
      bathroom_0: { wFt: 9, dFt: 5 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 12, yFt: 0 },
      dining_0: { xFt: 12, yFt: 6 },
      bedroom_1: { xFt: 0, yFt: 16 },
      kitchen_0: { xFt: 11, yFt: 16 },
      bedroom_0: { xFt: 0, yFt: 28 },
      bedroom_2: { xFt: 11, yFt: 28 },
      bathroom_0: { xFt: 11, yFt: 37 },
    },
  },

  // 6. 30x40 (1,200 sq ft) — 2BHK Classic Vaastu Home
  {
    id: "30x40_2bhk_north",
    name: "Classic 2BHK Vaastu Residence",
    type: "2BHK",
    plotSizeLabel: "30×40 (1,200 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 40,
    facing: "N",
    builtUpAreaSqFt: 748,
    totalSqFt: 1200,
    rating: "100% Vaastu Compliant",
    description:
      "The quintessential Indian family home plan. Spacious living hall with North-East entry, dedicated dining space, South-East modular kitchen, Ishanya Pooja mandir, and South-West Master Suite.",
    highlights: [
      "North-East Main Entry",
      "South-West Master Bedroom",
      "South-East Agni Modular Kitchen",
      "Formal Dining Hall & Pooja Mandir",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 2,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 10, dFt: 10 },
      pooja_0: { wFt: 5, dFt: 6 },
      bathroom_1: { wFt: 5, dFt: 6 },
      hall_0: { wFt: 14, dFt: 16 },
      bedroom_0: { wFt: 14, dFt: 16 },
      kitchen_0: { wFt: 10, dFt: 10 },
      bathroom_0: { wFt: 10, dFt: 6 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 0, yFt: 10 },
      bathroom_1: { xFt: 5, yFt: 10 },
      hall_0: { xFt: 10, yFt: 0 },
      bedroom_0: { xFt: 0, yFt: 16 },
      kitchen_0: { xFt: 14, yFt: 16 },
      bathroom_0: { xFt: 14, yFt: 26 },
    },
  },

  // 7. 30x40 (1,200 sq ft) — 3BHK Modern Family Residence
  {
    id: "30x40_3bhk_east",
    name: "Modern 3BHK Family Residence",
    type: "3BHK",
    plotSizeLabel: "30×40 (1,200 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 40,
    facing: "E",
    builtUpAreaSqFt: 755,
    totalSqFt: 1200,
    rating: "East-Facing Master Plan",
    description:
      "A high-demand 3-bedroom blueprint crafted for growing families. Generous living area, three well-proportioned bedrooms, separate dining and pantry store room.",
    highlights: [
      "3 Private Bedrooms",
      "East-Facing Entrance",
      "Dedicated Pantry / Store Room",
      "Optimal Privacy Zoning",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 3,
      bathroom: 2,
      pooja: 0,
      store: 1,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 11, dFt: 10 },
      kitchen_0: { wFt: 11, dFt: 6 },
      hall_0: { wFt: 13, dFt: 16 },
      bedroom_0: { wFt: 13, dFt: 16 },
      bedroom_1: { wFt: 11, dFt: 11 },
      bathroom_0: { wFt: 6, dFt: 5 },
      bathroom_1: { wFt: 5, dFt: 5 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      kitchen_0: { xFt: 0, yFt: 10 },
      hall_0: { xFt: 11, yFt: 0 },
      bedroom_0: { xFt: 0, yFt: 16 },
      bedroom_1: { xFt: 13, yFt: 16 },
      bathroom_0: { xFt: 13, yFt: 27 },
      bathroom_1: { xFt: 19, yFt: 27 },
    },
  },

  // 8. 30x40 (1,200 sq ft) — 2BHK South-Facing Haven
  {
    id: "30x40_2bhk_south",
    name: "Auspicious 2BHK South-Facing Haven",
    type: "2BHK",
    plotSizeLabel: "30×40 (1,200 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 40,
    facing: "S",
    builtUpAreaSqFt: 768,
    totalSqFt: 1200,
    rating: "100% Vaastu Compliant",
    description:
      "Expertly configured for South-facing plots following traditional Agni entrance pada. Places the front living hall in the South-East, kitchen in Agni zone, and master suite securely in South-West.",
    highlights: [
      "South-East Auspicious Entrance",
      "South-West Master Retreat",
      "North-East Light-Filled Pooja & Dining",
      "Cross-Breeze Optimized Bedrooms",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 1,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      bedroom_1: { wFt: 12, dFt: 14 },
      pooja_0: { wFt: 6, dFt: 6 },
      bathroom_0: { wFt: 6, dFt: 6 },
      dining_0: { wFt: 12, dFt: 8 },
      bedroom_0: { wFt: 13, dFt: 18 },
      kitchen_0: { wFt: 11, dFt: 8 },
      hall_0: { wFt: 11, dFt: 10 },
    },
    customPositions: {
      bedroom_1: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 12, yFt: 0 },
      bathroom_0: { xFt: 18, yFt: 0 },
      dining_0: { xFt: 12, yFt: 6 },
      bedroom_0: { xFt: 0, yFt: 14 },
      kitchen_0: { xFt: 13, yFt: 14 },
      hall_0: { xFt: 13, yFt: 22 },
    },
  },

  // 9. 30x40 (1,200 sq ft) — 3BHK West-Facing Sunset Home
  {
    id: "30x40_3bhk_west",
    name: "Sunset Glow 3BHK West-Facing Home",
    type: "3BHK",
    plotSizeLabel: "30×40 (1,200 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 40,
    facing: "W",
    builtUpAreaSqFt: 768,
    totalSqFt: 1200,
    rating: "West-Facing Master Plan",
    description:
      "A harmonious West-facing plan aligned with Varuna devata. Welcomes guests through the North-West entry lounge, with serene North-East pooja and commanding South-West master suite.",
    highlights: [
      "West-Facing Warm Living Lounge",
      "North-East Sacred Pooja Mandir",
      "South-West Master Sanctuary",
      "Dual Full Bathrooms & Dining",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 2,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 13, dFt: 16 },
      pooja_0: { wFt: 5, dFt: 6 },
      kitchen_0: { wFt: 6, dFt: 6 },
      dining_0: { wFt: 11, dFt: 10 },
      bedroom_0: { wFt: 13, dFt: 16 },
      bedroom_1: { wFt: 11, dFt: 11 },
      bathroom_0: { wFt: 6, dFt: 5 },
      bathroom_1: { wFt: 5, dFt: 5 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 13, yFt: 0 },
      kitchen_0: { xFt: 18, yFt: 0 },
      dining_0: { xFt: 13, yFt: 6 },
      bedroom_0: { xFt: 0, yFt: 16 },
      bedroom_1: { xFt: 13, yFt: 16 },
      bathroom_0: { xFt: 13, yFt: 27 },
      bathroom_1: { xFt: 19, yFt: 27 },
    },
  },

  // 10. 30x50 (1,500 sq ft) — 3BHK Contemporary Villa
  {
    id: "30x50_3bhk_east",
    name: "Contemporary 3BHK with Pooja & Dining",
    type: "3BHK",
    plotSizeLabel: "30×50 (1,500 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 50,
    facing: "E",
    builtUpAreaSqFt: 1009,
    totalSqFt: 1500,
    rating: "100% Vaastu Compliant",
    description:
      "A grand 1,500 sq ft layout with elongated depth. Expansive living hall, formal dining, chef's kitchen with attached utility/store, luxurious master suite with ensuite bath, and sacred pooja mandir.",
    highlights: [
      "Expansive 14×18 ft Living Salon",
      "Private Master Suite in South-West",
      "Dedicated Ishanya Pooja Room",
      "Walk-in Pantry Store & Dining",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 3,
      bathroom: 2,
      pooja: 1,
      store: 1,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 10, dFt: 12 },
      pooja_0: { wFt: 5, dFt: 6 },
      store_0: { wFt: 5, dFt: 6 },
      hall_0: { wFt: 14, dFt: 18 },
      bedroom_1: { wFt: 14, dFt: 12 },
      kitchen_0: { wFt: 10, dFt: 12 },
      bedroom_0: { wFt: 14, dFt: 12 },
      bathroom_0: { wFt: 5, dFt: 12 },
      bathroom_1: { wFt: 5, dFt: 12 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 0, yFt: 12 },
      store_0: { xFt: 5, yFt: 12 },
      hall_0: { xFt: 10, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 18 },
      kitchen_0: { xFt: 14, yFt: 18 },
      bedroom_0: { xFt: 0, yFt: 30 },
      bathroom_0: { xFt: 14, yFt: 30 },
      bathroom_1: { xFt: 19, yFt: 30 },
    },
  },

  // 11. 30x50 (1,500 sq ft) — 2BHK Sunlit Villa
  {
    id: "30x50_2bhk_north",
    name: "Sunlit 2BHK + Grand Living Villa",
    type: "2BHK",
    plotSizeLabel: "30×50 (1,500 sq ft)",
    plotWidthFt: 30,
    plotDepthFt: 50,
    facing: "N",
    builtUpAreaSqFt: 1009,
    totalSqFt: 1500,
    rating: "Premium North-Facing",
    description:
      "Designed for spacious living with extra-large bedroom suites, huge light-filled living salon, dining overlooking gardens, and maximum setbacks for cross breezes.",
    highlights: [
      "Massive 15×18 ft Living Hall",
      "Two Deluxe Master Bedrooms",
      "North-Facing Sunlit Foyer",
      "Generous Garden Setbacks",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 2,
      pooja: 1,
      store: 0,
      entrance: 0,
    },
    customDims: {
      pooja_0: { wFt: 9, dFt: 6 },
      dining_0: { wFt: 9, dFt: 12 },
      hall_0: { wFt: 15, dFt: 18 },
      bedroom_1: { wFt: 14, dFt: 14 },
      kitchen_0: { wFt: 10, dFt: 14 },
      bedroom_0: { wFt: 14, dFt: 10 },
      bathroom_0: { wFt: 5, dFt: 10 },
      bathroom_1: { wFt: 5, dFt: 10 },
    },
    customPositions: {
      pooja_0: { xFt: 0, yFt: 0 },
      dining_0: { xFt: 0, yFt: 6 },
      hall_0: { xFt: 9, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 18 },
      kitchen_0: { xFt: 14, yFt: 18 },
      bedroom_0: { xFt: 0, yFt: 32 },
      bathroom_0: { xFt: 14, yFt: 32 },
      bathroom_1: { xFt: 19, yFt: 32 },
    },
  },

  // 12. 35x50 (1,750 sq ft) — Traditional Kerala Courtyard Villa
  {
    id: "35x50_kerala_courtyard",
    name: "Traditional Kerala Courtyard Villa",
    type: "3BHK",
    plotSizeLabel: "35×50 (1,750 sq ft)",
    plotWidthFt: 35,
    plotDepthFt: 50,
    facing: "E",
    builtUpAreaSqFt: 1176,
    totalSqFt: 1750,
    rating: "100% Vaastu / Thachu Shastra",
    description:
      "Inspired by classical Kerala Nalukettu architecture. Highlights a grand central gathering hall, traditional granary store, pooja sanctum, and airy veranda cross-ventilation.",
    highlights: [
      "Nalukettu Central Gathering Hall",
      "Traditional Granary & Pantry Store",
      "Ishanya Sanctum Pooja Room",
      "Thachu Shastra Auspicious Grid",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 2,
      pooja: 1,
      store: 1,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 12, dFt: 14 },
      pooja_0: { wFt: 6, dFt: 6 },
      store_0: { wFt: 6, dFt: 6 },
      hall_0: { wFt: 16, dFt: 20 },
      bedroom_1: { wFt: 15, dFt: 12 },
      kitchen_0: { wFt: 13, dFt: 12 },
      bedroom_0: { wFt: 15, dFt: 10 },
      bathroom_0: { wFt: 6, dFt: 10 },
      bathroom_1: { wFt: 7, dFt: 10 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 0, yFt: 14 },
      store_0: { xFt: 6, yFt: 14 },
      hall_0: { xFt: 12, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 20 },
      kitchen_0: { xFt: 13, yFt: 20 },
      bedroom_0: { xFt: 0, yFt: 32 },
      bathroom_0: { xFt: 15, yFt: 32 },
      bathroom_1: { xFt: 21, yFt: 32 },
    },
  },

  // 13. 35x50 (1,750 sq ft) — Scandinavian Modernist Villa
  {
    id: "35x50_scandinavian_modern",
    name: "Scandinavian Modernist 3BHK Villa",
    type: "3BHK",
    plotSizeLabel: "35×50 (1,750 sq ft)",
    plotWidthFt: 35,
    plotDepthFt: 50,
    facing: "N",
    builtUpAreaSqFt: 1176,
    totalSqFt: 1750,
    rating: "Architectural Showcase",
    description:
      "Nordic plan. Floor-to-ceiling glazing, birch joinery, open dining, bedrooms set off the shared circulation.",
    highlights: [
      "Nordic Light Living & Great Room",
      "Minimalist Birch & Oak Chef Kitchen",
      "Open-Concept Dining",
      "Master Suite & Utility Store",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 1,
      pooja: 0,
      store: 1,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 16, dFt: 20 },
      dining_0: { wFt: 12, dFt: 20 },
      bedroom_1: { wFt: 14, dFt: 12 },
      kitchen_0: { wFt: 14, dFt: 12 },
      bedroom_0: { wFt: 14, dFt: 10 },
      bathroom_0: { wFt: 7, dFt: 10 },
      store_0: { wFt: 7, dFt: 10 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      dining_0: { xFt: 16, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 20 },
      kitchen_0: { xFt: 14, yFt: 20 },
      bedroom_0: { xFt: 0, yFt: 32 },
      bathroom_0: { xFt: 14, yFt: 32 },
      store_0: { xFt: 21, yFt: 32 },
    },
  },

  // 14. 40x60 (2,400 sq ft) — 3BHK Executive Luxury Bungalow
  {
    id: "40x60_3bhk_north",
    name: "Executive 3BHK Luxury Bungalow",
    type: "3BHK",
    plotSizeLabel: "40×60 (2,400 sq ft)",
    plotWidthFt: 40,
    plotDepthFt: 60,
    facing: "N",
    builtUpAreaSqFt: 1391,
    totalSqFt: 2400,
    rating: "100% Vaastu Compliant",
    description:
      "An estate-class single-level bungalow with an impressive double-door entrance, formal living salon, banquet-ready dining, gourmet kitchen, pantry store, and three grand king-size bedroom suites with attached baths.",
    highlights: [
      "Palatial Living Salon (19×22 ft)",
      "3 King-Size En-suite Bedrooms",
      "Gourmet Kitchen + Walk-in Store",
      "Sacred Ishanya Corner Pooja",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 3,
      bathroom: 3,
      pooja: 1,
      store: 1,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 14, dFt: 16 },
      pooja_0: { wFt: 6, dFt: 6 },
      store_0: { wFt: 8, dFt: 6 },
      hall_0: { wFt: 19, dFt: 22 },
      bedroom_1: { wFt: 16, dFt: 14 },
      kitchen_0: { wFt: 17, dFt: 14 },
      bedroom_0: { wFt: 16, dFt: 14 },
      bedroom_2: { wFt: 17, dFt: 14 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 0, yFt: 16 },
      store_0: { xFt: 6, yFt: 16 },
      hall_0: { xFt: 14, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 22 },
      kitchen_0: { xFt: 16, yFt: 22 },
      bedroom_0: { xFt: 0, yFt: 36 },
      bedroom_2: { xFt: 16, yFt: 36 },
    },
  },

  // 15. 40x60 (2,400 sq ft) — 4BHK Royal Grand Estate
  {
    id: "40x60_4bhk_east",
    name: "Royal 4BHK Grand Estate",
    type: "4BHK",
    plotSizeLabel: "40×60 (2,400 sq ft)",
    plotWidthFt: 40,
    plotDepthFt: 60,
    facing: "E",
    builtUpAreaSqFt: 1397,
    totalSqFt: 2400,
    rating: "East-Facing Royal Plan",
    description:
      "A complete 4-bedroom luxury layout offering separate zones for entertaining, private family gatherings, culinary prep, traditional pooja, and 4 dedicated master suites.",
    highlights: [
      "4 Deluxe Bedrooms",
      "East-Facing Auspicious Entrance",
      "Formal Dining & Modular Kitchen",
      "Dedicated Pooja & Storage",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 4,
      bathroom: 3,
      pooja: 1,
      store: 1,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 14, dFt: 14 },
      kitchen_0: { wFt: 14, dFt: 10 },
      hall_0: { wFt: 19, dFt: 24 },
      bedroom_1: { wFt: 16, dFt: 13 },
      bedroom_2: { wFt: 17, dFt: 13 },
      bedroom_0: { wFt: 16, dFt: 13 },
      bedroom_3: { wFt: 17, dFt: 13 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      kitchen_0: { xFt: 0, yFt: 14 },
      hall_0: { xFt: 14, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 24 },
      bedroom_2: { xFt: 16, yFt: 24 },
      bedroom_0: { xFt: 0, yFt: 37 },
      bedroom_3: { xFt: 16, yFt: 37 },
    },
  },

  // 16. 40x60 (2,400 sq ft) — Chettinad Heritage 4BHK Manor
  {
    id: "40x60_chettinad_heritage",
    name: "Chettinad Heritage 4BHK Manor",
    type: "4BHK",
    plotSizeLabel: "40×60 (2,400 sq ft)",
    plotWidthFt: 40,
    plotDepthFt: 60,
    facing: "S",
    builtUpAreaSqFt: 1650,
    totalSqFt: 2400,
    rating: "100% Traditional Heritage",
    description:
      "Inspired by the palatial mansions of Karaikudi and Chettinad. Features pillared front verandah entrance (Thinnai), grand central courtyard hall, traditional granary, and royal master suites.",
    highlights: [
      "Classical Thinnai Front Living Hall",
      "Pooja Sanctum in Auspicious Ishanya",
      "Grand Feasting Dining Hall",
      "Traditional Granary Store & Kitchen",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 3,
      bathroom: 2,
      pooja: 1,
      store: 1,
      entrance: 0,
    },
    customDims: {
      bedroom_2: { wFt: 16, dFt: 14 },
      pooja_0: { wFt: 8, dFt: 8 },
      store_0: { wFt: 9, dFt: 8 },
      dining_0: { wFt: 17, dFt: 10 },
      bedroom_1: { wFt: 16, dFt: 14 },
      kitchen_0: { wFt: 17, dFt: 10 },
      bedroom_0: { wFt: 16, dFt: 22 },
      hall_0: { wFt: 17, dFt: 22 },
    },
    customPositions: {
      bedroom_2: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 16, yFt: 0 },
      store_0: { xFt: 24, yFt: 0 },
      dining_0: { xFt: 16, yFt: 8 },
      bedroom_1: { xFt: 0, yFt: 14 },
      kitchen_0: { xFt: 16, yFt: 18 },
      bedroom_0: { xFt: 0, yFt: 28 },
      hall_0: { xFt: 16, yFt: 28 },
    },
  },

  // 17. 40x60 (2,400 sq ft) — Japanese Zen Minimalist Villa
  {
    id: "40x60_japanese_zen",
    name: "Japanese Zen Minimalist 3BHK Villa",
    type: "3BHK",
    plotSizeLabel: "40×60 (2,400 sq ft)",
    plotWidthFt: 40,
    plotDepthFt: 60,
    facing: "N",
    builtUpAreaSqFt: 1650,
    totalSqFt: 2400,
    rating: "Zen Architectural Design",
    description:
      "A serene sanctuary centered around Engawa porch connections, minimalist sliding partitions, open tea room dining, and peaceful nature views.",
    highlights: [
      "Engawa-Inspired Great Room",
      "Shoji Tea & Dining Pavilion",
      "Tatami Wood Guest Suite",
      "Private Master Sanctuary Wing",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 2,
      bathroom: 1,
      pooja: 0,
      store: 1,
      entrance: 0,
    },
    customDims: {
      hall_0: { wFt: 19, dFt: 22 },
      dining_0: { wFt: 14, dFt: 22 },
      bedroom_1: { wFt: 16, dFt: 14 },
      kitchen_0: { wFt: 17, dFt: 14 },
      bedroom_0: { wFt: 16, dFt: 14 },
      bathroom_0: { wFt: 8, dFt: 14 },
      store_0: { wFt: 9, dFt: 14 },
    },
    customPositions: {
      hall_0: { xFt: 0, yFt: 0 },
      dining_0: { xFt: 19, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 22 },
      kitchen_0: { xFt: 16, yFt: 22 },
      bedroom_0: { xFt: 0, yFt: 36 },
      bathroom_0: { xFt: 16, yFt: 36 },
      store_0: { xFt: 24, yFt: 36 },
    },
  },

  // 18. 50x80 (4,000 sq ft) — Palatial Courtyard Mansion
  {
    id: "50x80_4bhk_north",
    name: "Palatial 4BHK Courtyard Mansion",
    type: "4BHK",
    plotSizeLabel: "50×80 (4,000 sq ft)",
    plotWidthFt: 50,
    plotDepthFt: 80,
    facing: "N",
    builtUpAreaSqFt: 1969,
    totalSqFt: 4000,
    rating: "100% Vaastu Compliant",
    description:
      "A magnificent luxury mansion designed for expansive 50×80 plots. Grand royal salon, banquet dining, chef's kitchen, presidential master wing with private bath, and 3 guest/children suites.",
    highlights: [
      "Royal Grand Salon (24×26 ft)",
      "Presidential Master Wing (20×24 ft)",
      "Chef's Kitchen with Pantry & Store",
      "Traditional Ishanya Pooja Mandir",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 4,
      bathroom: 4,
      pooja: 1,
      store: 1,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 18, dFt: 18 },
      pooja_0: { wFt: 9, dFt: 8 },
      store_0: { wFt: 9, dFt: 8 },
      hall_0: { wFt: 24, dFt: 26 },
      bedroom_1: { wFt: 20, dFt: 18 },
      kitchen_0: { wFt: 22, dFt: 18 },
      bedroom_0: { wFt: 20, dFt: 24 },
      bedroom_2: { wFt: 22, dFt: 12 },
      bedroom_3: { wFt: 22, dFt: 12 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      pooja_0: { xFt: 0, yFt: 18 },
      store_0: { xFt: 9, yFt: 18 },
      hall_0: { xFt: 18, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 26 },
      kitchen_0: { xFt: 20, yFt: 26 },
      bedroom_0: { xFt: 0, yFt: 44 },
      bedroom_2: { xFt: 20, yFt: 44 },
      bedroom_3: { xFt: 20, yFt: 56 },
    },
  },

  // 19. 50x80 (4,000 sq ft) — Royal Sovereign Presidential Villa
  {
    id: "50x80_royal_sovereign",
    name: "Presidential 4BHK Sovereign Villa",
    type: "4BHK",
    plotSizeLabel: "50×80 (4,000 sq ft)",
    plotWidthFt: 50,
    plotDepthFt: 80,
    facing: "E",
    builtUpAreaSqFt: 2856,
    totalSqFt: 4000,
    rating: "East-Facing Sovereign Plan",
    description:
      "The pinnacle of residential architecture. Features an expansive 24×38 ft Grand Reception Hall, 18×22 ft Banquet Dining, full commercial chef kitchen, and 4 presidential en-suite suites.",
    highlights: [
      "Colossal 24×38 ft Reception Salon",
      "Formal Banquet Dining Room",
      "4 Deluxe Presidential Bedroom Suites",
      "Executive Commercial Chef's Kitchen",
    ],
    counts: {
      hall: 1,
      dining: 1,
      kitchen: 1,
      bedroom: 4,
      bathroom: 4,
      pooja: 0,
      store: 0,
      entrance: 0,
    },
    customDims: {
      dining_0: { wFt: 18, dFt: 22 },
      kitchen_0: { wFt: 18, dFt: 16 },
      hall_0: { wFt: 24, dFt: 38 },
      bedroom_1: { wFt: 21, dFt: 15 },
      bedroom_2: { wFt: 21, dFt: 15 },
      bedroom_0: { wFt: 21, dFt: 15 },
      bedroom_3: { wFt: 21, dFt: 15 },
    },
    customPositions: {
      dining_0: { xFt: 0, yFt: 0 },
      kitchen_0: { xFt: 0, yFt: 22 },
      hall_0: { xFt: 18, yFt: 0 },
      bedroom_1: { xFt: 0, yFt: 38 },
      bedroom_2: { xFt: 21, yFt: 38 },
      bedroom_0: { xFt: 0, yFt: 53 },
      bedroom_3: { xFt: 21, yFt: 53 },
    },
  },
];
